use_frameworks!

platform :ios, '9.0'

target 'taskit' do
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'KeychainAccess'
  pod 'JSONWebToken'
  pod 'Toast-Swift'
  pod 'ESPullToRefresh'
  pod 'Bugly'
  pod 'GoogleAnalytics'
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
  pod 'JWTDecode'
end

target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
