use_frameworks!

platform :ios, '9.0'

target 'taskit' do
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'KeychainAccess'
  pod 'JSONWebToken'
  pod 'Toast-Swift'
end
